Citizen.CreateThread(function()
  -- SASP
  AddTextEntry("sasp1", "(2011 - SASP) Ford CVPI")
  AddTextEntry("sasp2", "(2014 - SASP) Chevrolet Tahoe")
  AddTextEntry("sasp3", "(2016 - SASP) Ford Explorer")
  AddTextEntry("sasp4", "(2018 - SASP) Dodge Charger")
  AddTextEntry("sasp5", "(2018 - SASP) Dodge Charger K9")
  AddTextEntry("sasp6", "(2018 - SASP) Ford F-150")
  AddTextEntry("sasp7", "(2018 - SASP) Ford Mustang")
  AddTextEntry("sasp8", "(2018 - SASP) Ford Taurus")
  AddTextEntry("sasp9", "(2020 - SASP) Chevrolet Tahoe")
  AddTextEntry("sasp10", "(2020 - SASP) Chevrolet Tahoe K9")
  AddTextEntry("sasp11", "(2021 - SASP) Chevrolet Tahoe")
  AddTextEntry("sasp12", "(2021 - SASP) Dodge Durango")
  AddTextEntry("sasp13", "(SASP) BMW RT1200")
  AddTextEntry("sasp14", "(SASP) Boston Whaler")

  -- County (BCSO/LSSO)
  AddTextEntry("leoatv", "(BCSO | LSSO) ATV")

  -- Shared (LEO)
  AddTextEntry("airone", "(Emergency) Airone")

  -- Civ
  AddTextEntry("skyline", "(2002) Nissan Skyline GT-R34")
  AddTextEntry("srt392", "(2011) Dodge Challenger SRT8 392")
  AddTextEntry("f82", "(2015) BMW F82 M4")
  AddTextEntry("gtrnismo17", "(2017) Nissan GTR Nismo")
  AddTextEntry("na25", "(2011) Harley Davidson Road King")
  AddTextEntry("380sx", "(Management) Nissan 380SX Crazy")

  -- Weapons
  AddTextEntry("WEAPON_FNP90", "FNP90")
	AddTextEntry("WEAPON_HK516", "HK516")
  AddTextEntry("WEAPON_L119A2", "L119A2")
	AddTextEntry("WEAPON_M16", "M16")
	AddTextEntry("WEAPON_M82", "M82")
  AddTextEntry("WEAPON_M249S", "M249S")
  AddTextEntry("WEAPON_MDR2", "DT MDR 762x51")
  AddTextEntry("WEAPON_NSR9", "NSR9")
  AddTextEntry("WEAPON_P88", "P88")
  AddTextEntry("WEAPON_S101HR", "S101HR")
  AddTextEntry("WEAPON_SHWEND", "SHWEND")
  AddTextEntry("WEAPON_SR25", "SR-25")
  AddTextEntry("WEAPON_TOZ", "Toz Rifle")
  AddTextEntry("WEAPON_UZI9MM", "UZI 9MM")
  AddTextEntry("WEAPON_WINCHESTER", "Winchester Rifle")
  AddTextEntry("WEAPON_WINCHESTER", "Winchester Rifle")
  AddTextEntry("WEAPON_M45A1", "M45A1")
  AddTextEntry("WEAPON_G19", "Glock 19")
end)